### ISSUE TITLE
Missing Crypto Module

### ISSUE THREAD

**Issue by YuddiPrase** [arispati/src-crypto#1]
<img width="516" alt="Screen Shot 2020-11-05 at 12 45 53" src="https://user-images.githubusercontent.com/30163412/98202564-d8d59a00-1f64-11eb-99ed-101cc9496df1.png">

<img width="241" alt="Screen Shot 2020-11-05 at 12 46 16" src="https://user-images.githubusercontent.com/30163412/98202600-ea1ea680-1f64-11eb-9ac5-9a82b8a16a6a.png">

**Comment by YuddiPrase** [comment]
![Uploading Screen Shot 2020-11-05 at 12.47.17.png…]()

**Comment by arispati** [comment]
first of all, this module is for nodejs, not react native

it seem that you use this package with react native that doesn't include crypto module

or you can use this [react-native-crypto](https://github.com/tradle/react-native-crypto) instead of the nodejs crypto module
